### ISSUE TITLE
The Humane Tech Social Consciousness Project

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/humanetech-community-ideas#1]
Via LinkedIn I found a share by @andrewmurraydunn (Thanks, Andrew) to a [Wall-Street Journal article about Apple's new Screen Time app](https://community.humanetech.com/t/review-of-apple-ios-12-new-screen-time-app-that-helps-you-limit-your-iphone-usage/2331/2?u=aschrijver) that is integrated in iOS 12. Reading the comments of the WSJ article I came upon some terminology being used to indicate those highly addictive people that are constantly absorbed in their smartphone. The term was:

## "Phone Zombies"

>_"A person who gives preference to their smartphone and social media, even in social settings and in the company of others, which results in the person 'not really being there', like a zombie."_ (my definition)

## Idea: Introducing new terminology to affect cultural change

The comments used the word 'Phone zombie' casually, like it was a familiar, well-accepted slang word already. It seemed to me a highly effective way to make a person aware of their bad habits. Nobody wants to be called a 'phone zombie' by their friends. Using it deliberately can be a powerful tool to make people aware of their bad tech habits.

And it gave me the idea to use language strategically to change the culture and habits surrounding smartphone and social media use in positive ways. Language is power, after all. Culture drives behavior. 

> **Idea**: Change language -> _Affect culture_ -> _Drive behavior_

### The Humane Tech Social Consciousness Project

Changing language, by deliberately brainstorming terminology and injecting it into our daily conversations, is an activity that could be part of a larger CHT project with the goal of: _Influencing social consciousness with regards to technology use._  In other words: 'Weaponize' language to induce positive change.

Definition:
> **Social consciousness** 
>
> _"The collective self-awareness and experience of collectively shared social identity [..] and conscious awareness of being part of an interrelated community of others, [through which] individuals may experience social unity."_ (source: [Wikipedia](https://en.wikipedia.org/wiki/Social_consciousness))

Activities regarding language:

- Defining vocabulary, related imagery and meme's that are likely to stick in popular culture
- Determine ways to inject them into the conversation (e.g. social media strategy)
- Actively use and promote them in our day-to-day (online) communication

As an example of related imagery the artwork created by @micheleminno depict a great meme that can stick with the public:

![](/uploads/humanetech/original/1X/4f97d37baf5dbcfcf2fb66c667c3e39cd74baac8.jpg)

---

This idea was also introduced to the community forum: [Idea: "Smartphone Zombies", or: Deliberately using language to change habits and culture](https://community.humanetech.com/t/idea-smartphone-zombies-or-deliberately-using-language-to-change-habits-and-culture/2710)

**Comment by zed-neu2018** [comment]
Although I think the term is appropriate in a descriptive sense, I think a movement with "humane" in the title should be careful to avoid campaigning which uses language in a derogatory manner, or in a way that seems to insult or degrade (dehumanise) others.  The point is that human-beings are being hacked - it is not even the "fault" of the "phone zombies".  We need compassion and not condascension if this is to mean anything.

**Comment by aschrijver** [comment]
Yes, I agree @zed-neu2018 
I think 'careful' is the right word. The campaign should not be attacking, but compassionate indeed. Just enough to raise some awareness, a feeling - in a fun way - that 'sinking down into your smartphone' while with friends/family is something easily avoided.

**Comment by aschrijver** [comment]
This idea has become the [Phone Zombies](https://github.com/humanetech-community/awareness-program/tree/master/campaigns/phone-zombies) campaign in the HTC Awareness Program (proposed in issue https://github.com/humanetech-community/awareness-program/issues/25) and it is part of the [Speak Easy](https://github.com/humanetech-community/awareness-program/tree/master/themes/speak-easy) campaign theme (proposed in issue https://github.com/humanetech-community/humanetech-community-awareness/issues/19)

**Note**: The campaign documents that are linked might move to the [Community Hub](https://github.com/humanetech-community/community-hub/) project, so they are displayed in the website.
