### ISSUE TITLE
Agree on website hosting and possible CMS

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/humanetech-community-ideas#10]
Actual code is [here](https://github.com/humanetech-community/community-hub).
Actual hosting ([what does it mean](https://www.website.com/beginnerguide/webhosting/6/1/what-is-web-hosting?.ws)): ??

CMS: [what is it](https://en.wikipedia.org/wiki/Web_content_management_system)

**Comment by aschrijver** [comment]
## Current website: Jekyll

The current [Community Website](https://humanetech.community) was constructed by me, based on a set of open-source tools:

- [Jekyll](https://jekyllrb.com/): website framework that allows all pages to be defined as simple Markdown pages (the same format used in forum posts)
- [Github repository](https://github.com/humanetech-community/community-hub):  offers version / revision management and project management features (create issues, project boards, etc.)
- [Github Pages](https://guides.github.com/features/pages/): Automatically compiles and publishes a branch of the repository as a full-blown website, including a security certificate (to have `https` links).

### Pros

- Adheres to "Work Open, Lead Open".. all content and configuration is publicly visible
- Leverages Markdown as the simple format everywhere. No HTML knowldedge required to write pages and blog posts
- It is all open-source and the services used are all free, come at no additional costs
- (Non-technical) members can create content in normal forum posts and someone else can add them to the repository for instant display as HTML in the production website.
- Full control of the website HTML that is generated (i.e. easy to make it 'zero-trackers', remove Google, etc.)
- Jekyll is a so-called 'static site generator', i.e. it generates no frills static HTML that is more accessible with e.g. Javascript turned off, and reflects a trend for simplicity. This fits with humane tech take on things (avoid big javascript voodoo magic web apps).
- Extension exists to integrate with Discourse, to allow a discourse topic to be displayed below a page for creating comments.

### Cons

- Creating new page types / website sections requires knowledge of Python, Jekyll, HTML5, CSS and Javascript i.e. technical skills required
- Jekyll works best for relatively small websites, for larger ones the compilation times are getting really troublesome. The HTC website is intended/expected to be a lively, large website eventually.
- People doing website maintenance need to work with Github (creating PR's) and manage Markup metadata for proper inclusion of new content in the website.
- There are few out-of-the-box really attractive website designs. To have a 'cool' website requires the input and expertise of UX and Web designers.
- All website sections will be public. There are no hidden places where authorized users can prepare things out of public view. To facilitate this additional technical work + skills are needed.

### Status

The current website could be used as an MVP, but it does not reflect the new Mission and Vision. It should be re-made. If using it, at a later time we should probably re-do all the work if we move away from the Jekyll technology.

## Hugo CMS

I was researching [Hugo CMS](https://gohugo.io/) as an alternative to Jekyll. The same pros and cons apply to using Jekyll, with the following differences:

### Pros

- Hugo allows What-You-See-Is-What-You-Get (WYSIWYG) user-friendly UI's for page editing. There is no need to be working in the Github repository directly.

### Cons

- The technology needs to be hosted on a server (though this can be avoided by running locally)
- There are less plugins and extensions available than exist for Jekyll, e.g. no Discourse integration
- Hugo is written in Go, which is not as common a language as Python. We should use Hugo mostly as-is

### Status

I was researching this as an option. Besides Hugo there are plenty of other, similar options. Before making this choice a more thorough investigation is warranted. This option is less viable to create a quick MVP for the community website.

## Wordpress website

This option is about going for the most-widely used technology to create websites: [Wordpress](https://wordpress.org/).

### Pros

- Full-blown, full-feature CMS application with everything needed for building website available in the user interfaces of the application.
- Very little technical skill is required to setup and maintain the community website
- Many thousands of plugin extensions exist to extend the website
- Thousands of themes to choose from to set up a professionally looking layout

### Cons

- Either we allow advertising or need to pay to have a hosted version of Wordpress without ads.
- Wordpress does not adhere to "Work Open, Lead Open": a select group of authorized users manage the website in areas that are not publicly available.
- There is no full control of the HTML code that is generated by the website, e.g. depending on choice of Theme it can be hard to remove Google trackers (requires technical skills).

### Status

Wordpress looks like a good option not only to create a quick MVP, but as the standard CMS for the Community Website in the future. Enabling Wordpress is a single click on the current provider of the `humanetech.community` domain name [TransIP](https://transip.nl) and costs 66 Euros per year.

**Comment by micheleminno** [comment]
I'm for keeping the Jekyll site for now, changing it as extending it as much as we can do.
Hugo (like other similar solutions) seems to me a quite risky choice, requiring specific knowledge and expertise.
Wordpress would be good but is not free and the code can easily get messy and out of control, for what I could see.

**Comment by aschrijver** [comment]
Agreed. Let's keep things simple and go from what we already have.

**Comment by patmatsu** [comment]
Is anyone going to act on Free's offer? 

https://community.humanetech.com/t/setting-up-the-minimum-viable-product-for-the-community-website-choices/3791/

And what about the objections @healthyswimmer brought up? Do we need to address, discuss, resolve them? 

https://community.humanetech.com/t/setting-up-the-minimum-viable-product-for-the-community-website-choices/3791/

**Comment by aschrijver** [comment]
Yes, I responded to both posts:

- With the static website we are now building, hosting is not required
- We had agreed to put off funding decisions to either Q3 (Georges discussion) or after 10 months (OL7 vision stand)

**Comment by aschrijver** [comment]
Closing this issue. We go with the option to stick with Jekyll, hosted on Github. No further hosting is required.
