### ISSUE TITLE
Add link to code of conduct in the forum

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/humanetech-community-ideas#11]
Is it possible to add 'code of conduct' here in the menu?

![Screenshot 2019-04-15 at 15 16 40](https://user-images.githubusercontent.com/832220/56135770-bc909780-5f91-11e9-8959-16ea448207d8.png)

**Comment by healthyswimmer** [comment]
Yes you can, Arnold was able to add FAQ’s last year- so ask him how he did this...

**Comment by micheleminno** [comment]
@aschrijver, where can I go in settings in order to do that?

**Comment by micheleminno** [comment]
I managed to add it:

![Screenshot 2019-04-17 at 11 25 46](https://user-images.githubusercontent.com/832220/56276860-98ed5e80-6103-11e9-90dd-8780f061cb60.png)
