### ISSUE TITLE
Agree on the new category structure

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/humanetech-community-ideas#7]
### Awareness (296)

- Wellbeing (39)
- Relationships (11)
- Civics (38)
- Privacy (57)
- Children (69)
- Projects & campaigns (26)

### Advocacy (17)

- Projects & campaigns (3)

### Humane Design (86)

- Defining humane technology (21)
- Ethics (16)
- Exemplars (3)

### Community Commons (156)

- Community principles (7)
- Announcements (13)
- Events & meetups (66)
- About this forum (42)
- Help wanted (22)
- Introductions (2)

### Time Well Spent (120)

- Your apps & tools (58)
- News digest (12)
- Recommended reading (7)

**Comment by micheleminno** [comment]
## New categorization (draft)

### Society

  - Inclusion
  - Regulation 
  - Enlightened corporate thinking & practices
 - Rights & duties

### Wellbeing

- Health
- Inter-personal
- Children & teens 
- Mindfulness

### Alignment

  - Humane design
  - Ethics
  - Best-practices
  - Standards

### Freedom

  - Openness
  - Diversity
  - Security
  - Privacy

### Harms of Technology

- Harms to Wellbeing
- Harms to Society
- Harms to Freedom

### Focus

(These are all ongoing 'Programs') 

- Awareness Program
- Solutions Program
- Education Program
- Research Program
- Partners Program

### Central

- Vision & roadmap
- Announcements
- Events & meetups
- Judge my app
- I need help
- Feedback

**Comment by aschrijver** [comment]
Some suggestions for improvement:

- _Enlightened corporate thinking & practices_ --> too long, and 'corporate' too formal. I still like the term "Sustainable business", but can also be e.g. "Alternative business models".
- _Rights & duties_ --> duties is the wrong word (as in 'duty free'). Make this "Digital rights"? That's is a common term already used elsewhere.
- _Inter-personal_ --> Word choice, bit unclear.. 'between 2 or more people'. Better would be maybe to have it be just "Social"

**Comment by micheleminno** [comment]
New category suggestion from forum member @NSaikiwiki:

> do you think we should add some sort of feature that where there is an exchange of revenue, technology should seek to increase the personal wealth, not just health, of its users?

See discussion [here](https://community.humanetech.com/t/reflections-on-new-mission-and-vision-pyramids-of-humane-technology/3389/42).

**Comment by aschrijver** [comment]
There is now a problem in that the Pyramid of Freedom and Pyramid of Society levels do not match with the categorization anymore.

<table>
<th>pyramid</th><th>levels</th><th>categories</th>
<tr>
</tr>
<td>Pyramid of Freedom</td>
<td>
<ul>
<li>engagement</li>
<li>expression</li>
<li>flourishing</li>
</ul>
</td>
<td>
<ul>
<li>openness</li>
<li>diversity</li>
<li>security</li>
<li>privacy</li>
</ul>
</td>
</tr>
<tr>
<td>Pyramid of Society</td>
<td>
<ul>
<li>access</li>
<li>protection</li>
<li>safety</li>
</ul>
</td>
<td>
<ul>
<li>inclusion</li>
<li>regulation</li>
<li>sustainable business</li>
<li>digital rights</li>
</ul>
</td>
</tr>
</table>

Some shufling could improve this:

<table>
<th>pyramid</th><th>levels</th><th>categories</th>
<tr>
</tr>
<td>Pyramid of Freedom</td>
<td>
<ul>
<li>engagement</li>
<li><b>protection</b></li>
<li>flourishing</li>
</ul>
</td>
<td>
<ul>
<li>openness</li>
<li><b>digital rights</b></li>
<li>security</li>
<li>privacy</li>
</ul>
</td>
</tr>
<tr>
<td>Pyramid of Society</td>
<td>
<ul>
<li>access</li>
<li><b>expression</b></li>
<li>safety</li>
</ul>
</td>
<td>
<ul>
<li>inclusion</li>
<li><b>diversity</b></li>
<li>regulation</li>
<li>sustainable business</li>
</ul>
</td>
</tr>
</table>

WDYT?

**Comment by micheleminno** [comment]
Why do you think they don't match? I think protection (and digital rights) has more to do with society and expression (and diversity) more to do with freedom..

**Comment by aschrijver** [comment]
I was thinking re: Digital rights, that they give you freedom: Freedom of speech / information. and also Security and Privacy are in the Freedom pyramid, but there is no Level that reflects that.

Maybe we leave as-is for the moment, but I think in future we need to fine-tune the model a bit further, but we'll do that based on experience, practice and feedback.

**Comment by aschrijver** [comment]
The forum has been reorganized. 

Let's discuss future forum category changes on  the forum itself in the Feedback category.
