### ISSUE TITLE
Mapping from old to new category structure

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/humanetech-community-ideas#8]
Each topic must be revised to assign the correct category/categories, but as a first row stepì mapping rules can be applied from the old categories to the new ones.

**Comment by micheleminno** [comment]
## Mapping 

Each old topic must fit in a new category or subcategory (or in more than one). And since the new categorization is more powerful and comprehensive (as we hope) than the old one, there will be new topics in the new structure that would not have fallen under any old category (which is good).
For now let's make sure that we cover with the new categorization all the old categories.

*Important note*: Though there may be one-on-one mappings from old to new (sub)category, moving topics must be done on a case by case basis, emptying an old category and deleting afterwards. Otherwise new categories will be polluted from the start. We should also go through each topic (quickly) and delete irrelevant side-discussions or move them to other more-relevant / on-topic existing or new topics. Each moderator will address their own focus area first to divide the work.

### Mapping from each old category to a new category (or categories)

- **Awareness** -> 
  - Topic-by-topic recategorization (separating harms from solution)

- **Awareness / Wellbeing** -> 
  - Wellbeing
  - Wellbeing / Health
  - Wellbeing / Mindfulness

- **Awareness / Relationships** -> 
  - Wellbeing / Inter-personal

- **Awareness / Civics** ->
  - Society / Inclusion
  - Society / Regulation
  - Society / Rights & duties

- **Awareness / Privacy** ->
  - Freedom / Privacy

- **Awareness / Children** ->
  - Wellbeing / Children & teens 

- **Awareness / Projects & campaigns** ->
  - Awareness / Campaigns

- **Advocacy** ->
  - Society / Enlightened corporate thinking & practices

-  **Advocacy / Projects & campaigns** ->
   - This area no longer exists, advocacy/politics are on the CHT side. Map on case-by-case basis, or move to Uncategorized (for archiving or otherwise).

- **Engagement** ->
  - Same as above

- **Humane Design** ->
   - Alignment / Humane design

- **Humane Design / Defining humane technology** ->
   - Central / Vision & Roadmap (We have defined HT, no need for separate category)

- **Humane Design / Ethics** ->
   - Alignment / Ethics

- **Humane Design / Exemplars** ->
  - Focus / Solutions

- **Community Commons** ->
   - Central

- **Community Commons / Community principles**  ->
  - Central / Vision & roadmap

- **Community Commons / Announcements** ->
  - Central / Announcements

- **Community Commons / Events & meetups** ->
  - Central / Events & meetups

- **Community Commons / About this forum** ->
  - Central / I need help
  - Central / Feedback
  - FAQ
  - Contribution guidelines (from menu: Contributing)

- **Community Commons / Help wanted** ->
  - Central / I need help

- **Community Commons / Introductions** ->
  - Single topic "Introduce yourself", can be in 'Central / Announcements' (clearing this list from irrelevant "Hello" msgs)

- **Time Well Spent** ->
  - Case by case division to other categories

- **Time Well Spent / Your apps & tools** ->
  - Central / Judge my app

- **Time Well Spent / News digest** ->
-  This subcategory is dropped, but when there are news referring to HTC/CHT, then map to 'Central / Announcements'

- **Time Well Spent / Recommended reading** ->
  - This will be a project: Pat's Bookclub (location TBD)

**Comment by patmatsu** [comment]
Does this mean we have to go through all the topics on the forum?

**Comment by aschrijver** [comment]
Some of the categories can just be renamed and then sorted later. Others need to be checked one by one to divide them to correct new categories. Eventually, yes, all topics need to be checked.

This need not be too much work, and we'll divide based on CT member's focus area. When we do this, we can at the same time track lists of interesting topics that lend themselves to create community website content for (e.g. an Ideas list, book lists, etc.)

**Comment by aschrijver** [comment]
The forum reorganization is done, using the above mapping. Closing the issue.
